tiles = [
    {
        type:'dragon',
        value:'red_dragon',
        img:'images/tiles/MJd1.png',
        index:0
    },
    {
        type:'dragon',
        value:'green_dragon',
        img:'images/tiles/MJd2.png',
        index:1
    },
    {
        type:'dragon',
        value:'blue_dragon',
        img:'images/tiles/MJd3.png',
        index:2
    },
    {
        type:'direction',
        value:'east',
        img:'images/tiles/MJf1.png',
        index:3
    },
    {
        type:'direction',
        value:'south',
        img:'images/tiles/MJf2.png',
        index:4
    },
    {
        type:'direction',
        value:'west',
        img:'images/tiles/MJf3.png',
        index:5
    },
    {
        type:'direction',
        value:'north',
        img:'images/tiles/MJf4.png',
        index:6
    },
    {
        type:'red_flower',
        value:'1',
        img:'images/tiles/MJh1.png',
        index:7
    },
    {
        type:'red_flower',
        value:'2',
        img:'images/tiles/MJh2.png',
        index:8
    },
    {
        type:'red_flower',
        value:'3',
        img:'images/tiles/MJh3.png',
        index:9
    },
    {
        type:'red_flower',
        value:'4',
        img:'images/tiles/MJh4.png',
        index:10
    },
    {
        type:'blue_flower',
        value:'1',
        img:'images/tiles/MJh5.png',
        index:11
    },
    {
        type:'blue_flower',
        value:'2',
        img:'images/tiles/MJh6.png',
        index:12
    },
    {
        type:'blue_flower',
        value:'3',
        img:'images/tiles/MJh7.png',
        index:13
    },
    {
        type:'blue_flower',
        value:'4',
        img:'images/tiles/MJh8.png',
        index:14
    },
];

let size = tiles.length;

for(let [type,char] of [['character','w'],['dot','t'],['stick','s']]){
    for(let value = 1; value <= 9; value++){
        let newtile = {
            type,
            value,
            img:`images/tiles/MJ${char}${value}.png`,
            index:size++
        };
        tiles.push(newtile)
    }
}